### ISSUE TITLE
Material Design Elements Not Showing

### ISSUE THREAD

**Issue by ibrahim4851** [dsa28s/android-studio-apple-m1#10]
This is intel version

![intel](https://user-images.githubusercontent.com/67374998/115874496-d69cc480-a44c-11eb-8481-3fcddb50ca15.jpg)

And M1:
![m1](https://user-images.githubusercontent.com/67374998/115874558-e7e5d100-a44c-11eb-8b27-ae41ef2cbefb.jpg)

Also,
intel:
![intel2](https://user-images.githubusercontent.com/67374998/115874596-f03e0c00-a44c-11eb-990a-26a9818bdb7c.jpg)

M1:
![m1_2](https://user-images.githubusercontent.com/67374998/115874617-f633ed00-a44c-11eb-847a-88d30b286564.jpg)

**Comment by moffpage** [comment]
@dsa28s close this issue?
