### ISSUE TITLE
Good News,🎉🎉 Android Studio Arctic Fox Canary 15 contains preliminary support for Apple Silicon (arm64)

### ISSUE THREAD

**Issue by fangzb** [dsa28s/android-studio-apple-m1#12]
https://androidstudio.googleblog.com/2021/04/android-studio-arctic-fox-canary-15.html

**Comment by palvajk** [comment]
Here is the Apple Silicon build link: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.15/android-studio-2020.3.1.15-mac_arm.zip

**Comment by savked** [comment]
Is it just me, but @dsa28s's version works much faster than the Arctic Fox Canary 15?

**Comment by moffpage** [comment]
Yeah, his modifier version works faster especially after JDK change (to Zulu's arm build). However he told (reference to README.md) he'd update it every week until Google updates Android Studio itself. @dsa28s could you give us one more bug-fix / improvement update, please?)

**Comment by dsa28s** [comment]
I working hard to porting Canary 15 version. I know google release preliminary version of apple silicon, but performance is bad (I think)

So, I will continue this project until google release stable version of canary version.

Thank you!

**Comment by Fudoshiki** [comment]
Updated releases https://developer.android.com/studio/archive

**Comment by singun-lxd** [comment]
Arctic Fox Beta now!
https://androidstudio.googleblog.com/2021/05/android-studio-arctic-fox-beta-1.html

**Comment by abdhilabs** [comment]
> Arctic Fox Beta now!
> 
> https://androidstudio.googleblog.com/2021/05/android-studio-arctic-fox-beta-1.html

How the performance?

**Comment by hulkdx** [comment]
> > Arctic Fox Beta now!
> > https://androidstudio.googleblog.com/2021/05/android-studio-arctic-fox-beta-1.html
> 
> How the performance?

For me its really good.

**Comment by vlw** [comment]
Arctic Fox Beta 3 for Apple Silicon from Google: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.18/android-studio-2020.3.1.18-mac_arm.zip

**Comment by BillCooks** [comment]
Google newest 2021.1.1 Canary 2 for Apple Silicon:
 https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.2/android-studio-2021.1.1.2-mac_arm.zip

**Comment by moffpage** [comment]
I'm very much waiting for a new update from dsa28s!

**Comment by vanganistan** [comment]
> I'm very much waiting for a new update from dsa28s!

Same 🙄

**Comment by ghost** [comment]
> Google newest 2021.1.1 Canary 2 for Apple Silicon:
>  https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.2/android-studio-2021.1.1.2-mac_arm.zip

Did they fix the console not working issue ?

How does this build feel ?

**Comment by singun-lxd** [comment]
> > Google newest 2021.1.1 Canary 2 for Apple Silicon:
> > https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.2/android-studio-2021.1.1.2-mac_arm.zip
> 
> Did they fix the console not working issue ?
> 
> How does this build feel ?

@vanganistan 
You can replace libpty.dylib to resolve this problem.
The correct version can download from: https://github.com/dsa28s/android-studio-apple-m1/releases, and you can find it in path: Android Studio Preview.app/Contents/lib/pty4j-native/darwin/libpty.dylib

Or, you can do this:

> git clone https://github.com/JetBrains/pty4j.git
cd pty4j/native
clang -fPIC -c *.c
clang -shared -o libpty.dylib *.o
cp libpty.dylib "/Applications/Android Studio Preview.app/Contents/lib/pty4j-native/darwin/"

**Comment by moffpage** [comment]
I think we should close this issue

**Comment by fangzb** [comment]
> I think we should close this issue

Done~
