### ISSUE TITLE
Cannot open [canary-15]

### ISSUE THREAD

**Issue by diewland** [dsa28s/android-studio-apple-m1#13]
I'm [canary-14-2] user and It works very well. Need to use your latest build.
I found this message when try to open [canary-15]

```
“Android Studio Preview ARM64” is damaged and can’t be opened. You should move it to the Trash.
```

Thanks for great build.

**Comment by dsa28s** [comment]
Oh, really?! I will check this issue and re-upload release. Thank you!

**Comment by chen-paperkite** [comment]
Same problem here. Thanks for the great work.

**Comment by tylinux** [comment]
`sudo xattr -r -d com.apple.quarantine /Applications/Android\ Studio\ Preview\ ARM64.app` and reopen.

**Comment by londospark** [comment]
Could you please put this in the readme? That worked for me too!
