### ISSUE TITLE
Is there gonna be an update compatible with the new Bumblebee Arctic Fox Android Studio? 👀

### ISSUE THREAD

**Issue by moffpage** [dsa28s/android-studio-apple-m1#19]

**Comment by dsa28s** [comment]
Working progress.. Please wait until few days!

**Comment by moffpage** [comment]
Hi! Could you please tell if we're gonna get any updates at all? Or it's rather that you feel it ain't necessary

**Comment by moffpage** [comment]
Seems like the project is abandoned. @dsa28s Could you please tell if that's true? Anyway, thank you for doing this incredible work!

**Comment by AugustToko** [comment]
Or you can show the build script of android studio so we can do it ourselves😉

**Comment by moffpage** [comment]
@AugustToko where could I find it? I didn't really understand what you exactly wanted to say...

**Comment by dsa28s** [comment]
I'm sorry. I've been too busy at work lately.
It's currently in progress, so I'll upload the release soon. (Maybe one days later? :))

**Comment by dsa28s** [comment]
Hmm... I don't think need to proceed with this project anymore.

Because, I just tried the official version, and I checked the basic features such as terminals, layout preview, build.. in the Bumblebee version.
I will use it a little more and decide whether to stop supporting the project.

Here is official version of Android Studio arm64 version download link

- Android Studio Arctic Fox 2020.3.1 arm64
	- https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.19/android-studio-2020.3.1.19-mac_arm.zip
- Android Studio Bumblebee 2021.1.1 arm64
	- https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.2/android-studio-2021.1.1.2-mac_arm.zip

**Comment by shaycormac** [comment]
> Hmm... I don't think need to proceed with this project anymore.
> 
> Because, I just tried the official version, and I checked the basic features such as terminals, layout preview, build.. in the Bumblebee version.
> I will use it a little more and decide whether to stop supporting the project.
> 
> Here is official version of Android Studio arm64 version download link
> 
> * Android Studio Arctic Fox 2020.3.1 arm64
>   
>   * https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.19/android-studio-2020.3.1.19-mac_arm.zip
> * Android Studio Bumblebee 2021.1.1 arm64
>   
>   * https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.2/android-studio-2021.1.1.2-mac_arm.zip

Hi, hello, first of all, thank you for making such a great unofficial version, you gave the two official versions I used before, my configuration is 16G + 256G, but using the official version still obviously feel lagging, especially when editing the code, then a friend sent me the version you developed, I use, obviously smooth and efficient, so I mean you can use the official version first The official version for a period of time before deciding whether to continue to maintain, once again, thank you for the unofficial version!

**Comment by dsa28s** [comment]
@shaycormac Thank you for reply! Then I'll work on it today ~ tomorrow and release it.

**Comment by moffpage** [comment]
I'm so excited for this!

**Comment by bunjix** [comment]
Thanks for your work.
Just saw the new release you just deployed. Do you plan to also work on Bumblebee 2021.1.1 Canary 2 ?

**Comment by pedrosax** [comment]
In case you are still looking for an Apple M1 build of Android Studio, you can just get them directly from the Android Studio [download page](https://developer.android.com/studio), see this tweet: https://twitter.com/androidstudio/status/1429817771756376064

**Comment by moffpage** [comment]
Yeah I think we might close this for now
