### ISSUE TITLE
The rendering library could not be initialized

### ISSUE THREAD

**Issue by yodyyyy** [dsa28s/android-studio-apple-m1#2]
```
com.android.tools.idea.layoutlib.RenderingException: The rendering library could not be initialized
	at com.android.tools.idea.layoutlib.LayoutLibraryLoader.loadImpl(LayoutLibraryLoader.java:91)
	at com.android.tools.idea.layoutlib.LayoutLibraryLoader.load(LayoutLibraryLoader.java:120)
	at org.jetbrains.android.sdk.AndroidTargetData.getLayoutLibrary(AndroidTargetData.java:182)
	at org.jetbrains.android.sdk.AndroidTargetData.getLayoutLibrary(AndroidTargetData.java:174)
	at com.android.tools.idea.rendering.RenderService$RenderTaskBuilder.lambda$build$2(RenderService.java:645)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/8794792/114278788-922c2480-9a5b-11eb-8337-696c0e7fb7ee.png)

From SO to fix this by disable new layout rendering engine but can't find this option in experimental settings.
Thank you

**Comment by myung-nyun** [comment]
so do i

**Comment by VamChao** [comment]
Me too.

**Comment by sedgwickz** [comment]
I encountered the same issue.

**Comment by dsa28s** [comment]
Ok. I found this issue. The prebuilt android layoutlib native binary architecture is `x86_64`, but Runtime is `arm64` architecture. (Simply, architecture is not match)

So, I working hard to rebuild `layoutlib/libandroid_runtime.dylib` from android fullsource for `darwin-arm64` architecture. Please wait a little longer. Thank you.

**Comment by VamChao** [comment]
> Ok. I found this issue. The prebuilt android layoutlib native binary architecture is `x86_64`, but Runtime is `arm64` architecture. (Simply, architecture is not match)
> 
> So, I working hard to rebuild `layoutlib/libandroid_runtime.dylib` from android fullsource for `darwin-arm64` architecture. Please wait a little longer. Thank you.

非常感谢你的贡献，辛苦啦。

**Comment by dsa28s** [comment]
<img width="1036" alt="Screen Shot 2021-04-16 at 6 59 30 PM" src="https://user-images.githubusercontent.com/10934461/115008344-f7619900-9ee5-11eb-9cf9-62058231af51.png">

Current status. About 70% of the work is done.
Google does not support `layoutlib/libandroid_runtime.dylib` build guide. So it's taking a lot of time.

Can anyone who knows how to build above help me?

**Comment by dsa28s** [comment]
<img width="1202" alt="Screen Shot 2021-04-17 at 1 57 09 AM" src="https://user-images.githubusercontent.com/10934461/115058485-43c9ca80-9f20-11eb-83dd-6c722c070c89.png">

Oh my god! Fix this issue!!

**Comment by dsa28s** [comment]
https://github.com/dsa28s/android-studio-apple-m1/releases/tag/canary-14-2
Here is patched version of fixed this issue. Try it!

**Comment by savked** [comment]
It is now running, however I cannot see any devices in profiler to select.

**Comment by VamChao** [comment]
So cool !!!

**Comment by dsa28s** [comment]
@axlyody Please download patched version, and check this issue fixed.
If you check, I'll close the issue.

**Comment by savked** [comment]
@dsa28s I had to disable some "rendering sandbox" thing that popped up as an error when I first loaded the layout, and then it worked... After I disabled that, I got the pop up that said: 
<img width="281" alt="Screenshot 2021-04-17 at 14 11 42" src="https://user-images.githubusercontent.com/22063573/115112735-35fb6000-9f87-11eb-955b-9ea3893ad770.png">

**Comment by yodyyyy** [comment]
> @axlyody Please download patched version, and check this issue fixed.
> If you check, I'll close the issue.

Nice 👍
Thank you

**Comment by kofi-k** [comment]
> https://github.com/dsa28s/android-studio-apple-m1/releases/tag/canary-14-2
> Here is patched version of fixed this issue. Try it!

How do I implement this in my android studio?

**Comment by ghost** [comment]
> Ok. I found this issue. The prebuilt android layoutlib native binary architecture is `x86_64`, but Runtime is `arm64` architecture. (Simply, architecture is not match)
> 
> So, I working hard to rebuild `layoutlib/libandroid_runtime.dylib` from android fullsource for `darwin-arm64` architecture. Please wait a little longer. Thank you.

Hey there
I am trying to port android studio to linux arm64. i am halfway done in my work. I am also facing this same issue. can you tell me how you built this lib for darwin?
so i can follow the process to make for linux arm64
thanks

**Comment by victorwads** [comment]
Hey @dsa28s i'm runing Android Studio inside my Android Tablet, with a Linux Aarch64 sideload on my Android.

Everything that i had to user, except the ComposePreview is working.

Probally if i rebuild this Layout Like for aarch64 will solve the problem. But i never did that before. i got the SDK build tools 33.0.3 aarch64 from another gut that knows how to build native thing.

Can u help me with this?
