### ISSUE TITLE
Profiler not working, shows "Nothing to show"

### ISSUE THREAD

**Issue by savked** [dsa28s/android-studio-apple-m1#4]
Probably the similar rendering issue as for the XML preview?

<img width="2520" alt="Screenshot 2021-04-15 at 15 07 29" src="https://user-images.githubusercontent.com/22063573/114874230-69f64a00-9dfc-11eb-9d65-e8e063a086df.png">

**Comment by dsa28s** [comment]
https://github.com/dsa28s/android-studio-apple-m1/releases/tag/canary-14-2
Here is patched version of fixed this issue. Try it!

**Comment by savked** [comment]
Getting these pop ups when I try to run it: 
<img width="527" alt="Screenshot 2021-04-16 at 19 30 19" src="https://user-images.githubusercontent.com/22063573/115062120-46a9c880-9eea-11eb-8b7e-c54eefe3497f.png">

Thank you so much for your hard work!!!

**Comment by dsa28s** [comment]
@savked Could you please uninstall the previous canary version and install it again?

**Comment by savked** [comment]
@dsa28s I have, that's after it :/

**Comment by dsa28s** [comment]
@savked Hmm.. Could you please execute the following command at the terminal and re-launch android studio?

```bash
$ xattr -cr /Applications/Android\ Studio\ Preview \ARM64.app
```

**Comment by savked** [comment]
Should be `xattr -cr /Applications/Android\ Studio\ Preview\ ARM64.app`, but no doesn't work still..

**Comment by dsa28s** [comment]
@savked I uploaded it again. Please try it.

**Comment by savked** [comment]
It is now running thanks, however I cannot see any devices in profiler to select. Both real or emulator device..

**Comment by dsa28s** [comment]
> however I cannot see any devices in profiler to select. Both real or emulator device..

@savked Please submit the new issue for what you said. Thank you.
This issue will closing.
