### ISSUE TITLE
Cannot open Local Termnial. 

### ISSUE THREAD

**Issue by Starmel** [dsa28s/android-studio-apple-m1#5]
Thank you so much for porting Android Studio!!

Steps: 
 * Open terminal.

Output: 
```
Cannot open Local Terminal
Failed to start [/bin/zsh, --login, -i] in /projectdir


See your idea.log (Help | Show Log in Finder) for the details.
```

idea.log content: 
https://gist.github.com/Starmel/bde7662384920bc8558d41778b4567b0

**Comment by dsa28s** [comment]
OK. I found this issue. Next release will fix this issue.
Thank you so much!!

**Comment by dsa28s** [comment]
<img width="770" alt="Screen Shot 2021-04-17 at 12 47 59 AM" src="https://user-images.githubusercontent.com/10934461/115050300-91d9d080-9f16-11eb-8a86-b42701a5f8c2.png">

**Comment by Starmel** [comment]
So cool. How can I buy you coffee?

**Comment by dsa28s** [comment]
@Starmel Thank you!!

https://github.com/dsa28s/android-studio-apple-m1/releases/tag/canary-14-2
Here is patched version of fixed this issue. Try it!

**Comment by dsa28s** [comment]
@Starmel Please download patched version, and check this issue fixed.
If you check, I'll close the issue.

**Comment by aky0419** [comment]
Hi @dsa28s Is there a regression? I have the canary 15, built on 4/28, and still have the similar issue.
![image](https://user-images.githubusercontent.com/60959463/118447751-00d94f00-b6a6-11eb-9120-545e6c51082f.png)
![image](https://user-images.githubusercontent.com/60959463/118447875-1fd7e100-b6a6-11eb-9de0-25a0877fd6e2.png)

**Comment by dsa28s** [comment]
> Hi @dsa28s Is there a regression? I have the canary 15, built on 4/28, and still have the similar issue.
> 
> ![image](https://user-images.githubusercontent.com/60959463/118447751-00d94f00-b6a6-11eb-9120-545e6c51082f.png)
> 
> ![image](https://user-images.githubusercontent.com/60959463/118447875-1fd7e100-b6a6-11eb-9de0-25a0877fd6e2.png)
> 
> 

Current release already fixed this issue, but offical canary 15 version affected this issue.

**Comment by aky0419** [comment]
Thanks for the quick response. I have the m1 cpu macbook and it seems only the 15 support the the arm64. Hopefully this will get patched very soon in the arm64 version.

**Comment by maxcorrads** [comment]
Hi, also in `Android Studio Arctic Fox | 2020.3.1 Beta 1 Build #AI-203.7717.56.2031.7360992, built on May 14, 2021` this is not working. Does anyone know how to fix it? Thank you

**Comment by albertbuchard** [comment]
bumblebee 2021.1.1 solved it for me

**Comment by dsa28s** [comment]
@maxcorrads @aky0419 I have found this issue. It will be patched at Arctic Fox Beta 1 / BumbleBee 2021.1.1.

@albertbuchard Bumblebee official arm64 version is not released. :( So, I will patched bumblebee version soon. Thank you.

**Comment by Dararii** [comment]
Still found the issue on Arctic Fox Beta 3. Any solution?

**Comment by b4s36t4** [comment]
Yea, after doing so much digging I found the solution that worked for me here.!

https://github.com/JetBrains/pty4j/issues/82#issuecomment-835337224
@Dararii

**Comment by Dararii** [comment]
> Yea, after doing so much digging I found the solution that worked for me here.!
> 
> [JetBrains/pty4j#82 (comment)](https://github.com/JetBrains/pty4j/issues/82#issuecomment-835337224)
> @Dararii

Solved my issue. Thank you so much. For anyone who follow the solution, just ensure you restart the Studio afterwards.

**Comment by ajith-ab** [comment]
Hey,
I had the same issue but on macOS with an M1 processor and Android Studio Preview.
The below solution works but I had to change the commands slightly. I'm sharing it here for anyone with the same issue on M1 Mac.

First of all you need to Open the  Android Studio Preview app and close completely from you docks. and run the following commands.

```bash 
git clone https://github.com/JetBrains/pty4j.git
cd pty4j/native
clang -fPIC -c *.c
clang -shared -o libpty.dylib *.o
cp libpty.dylib "/Applications/Android Studio Preview.app/Contents/lib/pty4j-native/darwin/"
```

**Comment by fugogugo** [comment]
I just downloaded latest Arctic Fox and this happen again 

above command doesn't work as well
please reopen this issue

=========================

Android Studio Arctic Fox | 2020.3.1 Beta 4
Build #AI-203.7717.56.2031.7435690, built on June 8, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true

**Comment by jeevakalaiselvam** [comment]
@fugogugo , I can confirm. I have the same issue as well.
![image](https://user-images.githubusercontent.com/77735712/123340433-d498d400-d569-11eb-8c1c-a3695e9d0b89.png)

![image](https://user-images.githubusercontent.com/77735712/123340594-10cc3480-d56a-11eb-8f0d-7b1e868bca39.png)

**Comment by b4s36t4** [comment]
@jeevakalaiselvam , Have you tried the solutions provided above?! I had the same issues with `arctic fox` version, but the above solution had fixed it.

**Comment by ghost** [comment]
> Hey,
> I had the same issue but on macOS with an M1 processor and Android Studio Preview.
> The below solution works but I had to change the commands slightly. I'm sharing it here for anyone with the same issue on M1 Mac.
> 
> First of all you need to Open the Android Studio Preview app and close completely from you docks. and run the following commands.
> 
> ```shell
> git clone https://github.com/JetBrains/pty4j.git
> cd pty4j/native
> clang -fPIC -c *.c
> clang -shared -o libpty.dylib *.o
> cp libpty.dylib "/Applications/Android Studio Preview.app/Contents/lib/pty4j-native/darwin/"
> ```

This worked to me.
THanks

**Comment by Nomiracle** [comment]
> Hey,
> I had the same issue but on macOS with an M1 processor and Android Studio Preview.
> The below solution works but I had to change the commands slightly. I'm sharing it here for anyone with the same issue on M1 Mac.
> 
> First of all you need to Open the Android Studio Preview app and close completely from you docks. and run the following commands.
> 
> ```shell
> git clone https://github.com/JetBrains/pty4j.git
> cd pty4j/native
> clang -fPIC -c *.c
> clang -shared -o libpty.dylib *.o
> cp libpty.dylib "/Applications/Android Studio Preview.app/Contents/lib/pty4j-native/darwin/"
> ```

It also worked for me,Thanks :)

Android Studio Arctic Fox | 2020.3.1 Beta 4
Build #AI-203.7717.56.2031.7435690, built on June 8, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true

**Comment by tabvn** [comment]
<img width="841" alt="Screen Shot 2021-06-30 at 22 15 28" src="https://user-images.githubusercontent.com/186773/123986642-ae06ed00-d9f0-11eb-8879-f987ca4292ef.png">
same issue.

**Comment by ghost** [comment]
> <img alt="Screen Shot 2021-06-30 at 22 15 28" width="841" src="https://user-images.githubusercontent.com/186773/123986642-ae06ed00-d9f0-11eb-8879-f987ca4292ef.png">
> 
> same issue.

are you using Android Studio Arctic Fox ?

**Comment by dsa28s** [comment]
https://github.com/dsa28s/android-studio-apple-m1/releases/tag/arctic-fox-beta4

Here is patched version of Android Studio Arctic Fox Beta 4. It is included fix terminal not working.

**Comment by tabvn** [comment]
@dsa28s  yes i am
<img width="686" alt="Screen Shot 2021-06-30 at 22 58 45" src="https://user-images.githubusercontent.com/186773/123993563-bbbf7100-d9f6-11eb-8c02-bc09087cf8c5.png">

**Comment by tabvn** [comment]
<img width="1461" alt="Screen Shot 2021-07-03 at 12 52 43" src="https://user-images.githubusercontent.com/186773/124344622-918bd000-dbfd-11eb-8aea-7edf4320c95a.png">
Beta 5 still has issue.

**Comment by mochadwi** [comment]
> Yea, after doing so much digging I found the solution that worked for me here.!
> 
> [JetBrains/pty4j#82 (comment)](https://github.com/JetBrains/pty4j/issues/82#issuecomment-835337224)
> @Dararii

This also solved my issue. Thank you~ 

I'm using `Arctic Fox Beta 5`

**Comment by fugogugo** [comment]
> Hey,
> I had the same issue but on macOS with an M1 processor and Android Studio Preview.
> The below solution works but I had to change the commands slightly. I'm sharing it here for anyone with the same issue on M1 Mac.
> 
> First of all you need to Open the Android Studio Preview app and close completely from you docks. and run the following commands.
> 
> ```shell
> git clone https://github.com/JetBrains/pty4j.git
> cd pty4j/native
> clang -fPIC -c *.c
> clang -shared -o libpty.dylib *.o
> cp libpty.dylib "/Applications/Android Studio Preview.app/Contents/lib/pty4j-native/darwin/"
> ```

Whoaaa this worked! 
Stupid me not notice the wrong path. thank youuuu!

**Comment by Dararii** [comment]
Solved on the Arctic Fox RC 1 build.

**Comment by Shimingli** [comment]
thanks , good ideas

**Comment by teddichiiwa** [comment]
> Hey, I had the same issue but on macOS with an M1 processor and Android Studio Preview. The below solution works but I had to change the commands slightly. I'm sharing it here for anyone with the same issue on M1 Mac.
> 
> First of all you need to Open the Android Studio Preview app and close completely from you docks. and run the following commands.
> 
> ```shell
> git clone https://github.com/JetBrains/pty4j.git
> cd pty4j/native
> clang -fPIC -c *.c
> clang -shared -o libpty.dylib *.o
> cp libpty.dylib "/Applications/Android Studio Preview.app/Contents/lib/pty4j-native/darwin/"
> ```

It works like a charm 👍
