### ISSUE TITLE
The JDK is still "Intel", please replace it

### ISSUE THREAD

**Issue by lennondotw** [dsa28s/android-studio-apple-m1#6]
The JDK in the Android Studio release is still for Intel processor. I replaced it with Zulu JDK, everything works well.

This is where I download the JDK: [Java 11, macOS, ARM64, Zulu JDK](https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk)

You should replace this entire folder:
<img width="709" alt="Screen Shot 2021-04-19 at 22 48 03" src="https://user-images.githubusercontent.com/26853900/115255890-51ba5e00-a161-11eb-8ef6-037ba3e4a955.png">

Then your Android Studio will runs smoother.
![Screen Shot 2021-04-19 at 22 51 58](https://user-images.githubusercontent.com/26853900/115256694-0c4a6080-a162-11eb-88ff-3805d90633c7.png)

**Thanks for your arm64 build!**

**Comment by dsa28s** [comment]
Oh, Thank you for submit issue! I missed change architecture to arm64 Embedded JDK.

I will patch with your solution.
It will be applying at Next release.

**Comment by londospark** [comment]
For some reason macOS refuses to run this preview when I've done that, I'm not sure if I've messed it up as I haven't used a Mac for a long time, can't wait to see it incorporated. Running this version is already so much smoother than the Rosetta one

**Comment by moffpage** [comment]
@dsa28s close this issue?

**Comment by lennondotw** [comment]
Fixed. [Arctic Fox Canary 15](https://github.com/dsa28s/android-studio-apple-m1/releases/tag/canary-15)
